name: Zwift squasher
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */3 *"
jobs:
  zwift_squasher:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: netbrain/free-disk-space-action@v0.0.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Squash zwift image
        run: |
          set -x
          export VERSION=$(curl -s http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml | grep -oP 'sversion="\K.*?(?=")' | cut -f 1 -d ' ')
          export BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "Latest zwift version is $VERSION"

          echo "Pushing latest version to presquash"
          docker pull netbrain/zwift:$VERSION
          docker tag netbrain/zwift:$VERSION netbrain/zwift:$VERSION-presquash

          echo "Starting squash"
          docker build -t netbrain/zwift:$VERSION -f squash.Dockerfile .
          docker tag netbrain/zwift:$VERSION netbrain/zwift:latest

          echo "Starting push"
          docker push netbrain/zwift:$VERSION-presquash
          docker push netbrain/zwift:latest
          docker push netbrain/zwift:$VERSION
